call do1.bat logo.png tn\logo.png 
call do1.bat logobg.png tn\logobg.png 
call do1.bat babyworld.jpg tn\babyworld.jpg 
call do1.bat meraviglie.jpg tn\meraviglie.jpg 
call do1.bat mongolfiera.jpg tn\mongolfiera.jpg 
call do1.bat nido2_150096.jpg tn\nido2_150096.jpg 
call do1.bat primavera.jpg tn\primavera.jpg 
call do1.bat primavera_orig.jpg tn\primavera_orig.jpg 
call do1.bat principe.jpg tn\principe.jpg 
